name = "sokubaireji"
main = "worker/index.ts"
compatibility_date = "2025-01-01"
compatibility_flags = ["nodejs_compat"]

[assets]
directory = "./dist"
binding = "ASSETS"
not_found_handling = "single-page-application"

[[d1_databases]]
binding = "DB"
database_name = "sokubaireji-db"
database_id = "a314516b-d23c-44cd-b749-38d62f257cbe"

[browser]
binding = "BROWSER"

